                .include "gcommon.s65"
                .include "zx02-optim.s65"

;-------------------------------------------------------------------------

*=$70
                .dsection zp
                .dsection zx02_zp
                .cerror *>$90

;-------------------------------------------------------------------------

zx02_out_addr=$2b00
                .cerror zx02_out_addr<gedmc_levels_org+level_data_pages*256
                
;-------------------------------------------------------------------------

*=$8000-(end-begin)-2

                .word main
begin:
                .dsection data
                .dsection code
                .dsection zx02_code
end:
                
;-------------------------------------------------------------------------

                .section zp
                .endsection

                .section code
main:
                jmp full_decomp
                .endsection code

;-------------------------------------------------------------------------

                .section data
zx02_comp_data: .binary '../build/title.zx02'
                .endsection

;-------------------------------------------------------------------------
