                .include "../submodules/beeb/include/beeb.s65"
                
*=$900
                
                .cerror (udgs_end-udgs)%8!=0,""
                
start:
                ldx #0
chars_loop:
                lda #23
                jsr oswrch
ch=*+1
                lda #224
                jsr oswrch
                ldy #8
char_loop:
                lda udgs,x
                jsr oswrch
                inx
                dey
                bne char_loop
                inc ch
                cpx #udgs_end-udgs
                bcc chars_loop
                rts
                
udgs:
                ; Fancy digits
;224
                .byte %11111110 
                .byte %10000010 
                .byte %10000010 
                .byte %10000010 
                .byte %10000110 
                .byte %10000110 
                .byte %10000110 
                .byte %11111110 

;225
                .byte %00001100 
                .byte %00001100 
                .byte %00001100 
                .byte %00001100 
                .byte %00011100 
                .byte %00011100 
                .byte %00011100 
                .byte %00011100 

;226
                .byte %11111110 
                .byte %10000010 
                .byte %10000010 
                .byte %00000010 
                .byte %11111110 
                .byte %11000000 
                .byte %11000000 
                .byte %11111110 

;227
                .byte %11111100 
                .byte %10000100 
                .byte %10000100 
                .byte %00000100 
                .byte %00111110 
                .byte %10000110 
                .byte %10000110 
                .byte %11111110 

;228
                .byte %11111100 
                .byte %10000100 
                .byte %10000100 
                .byte %10000100 
                .byte %10000100 
                .byte %11111110 
                .byte %00001100 
                .byte %00001100 

;229
                .byte %11111110 
                .byte %10000000 
                .byte %10000000 
                .byte %11111110 
                .byte %00000110 
                .byte %00000110 
                .byte %10000110 
                .byte %11111110 

;230
                .byte %11111110 
                .byte %10000010 
                .byte %10000010 
                .byte %10000000 
                .byte %11111110 
                .byte %10000110 
                .byte %10000110 
                .byte %11111110 

;231
                .byte %11111110 
                .byte %00000010 
                .byte %00000010 
                .byte %00000010 
                .byte %00000110 
                .byte %00000110 
                .byte %00000110 
                .byte %00000110 

;232
                .byte %01111100 
                .byte %01000100 
                .byte %01000100 
                .byte %11111110 
                .byte %10000110 
                .byte %10000110 
                .byte %10000110 
                .byte %11111110 

;233
                .byte %11111110 
                .byte %10000010 
                .byte %10000010 
                .byte %11111110 
                .byte %00000110 
                .byte %00000110 
                .byte %00000110 
                .byte %00000110

                ; "BONUS"

;234
                .byte %00000000 
                .byte %11100011 
                .byte %10010100 
                .byte %10010100 
                .byte %10100100 
                .byte %10010100 
                .byte %10010100 
                .byte %11100011 

;235
                .byte %00000000 
                .byte %00100101 
                .byte %10110101 
                .byte %10110101 
                .byte %10111101 
                .byte %10101101 
                .byte %10101101 
                .byte %00100100

;236
                .byte %00000000 
                .byte %00100111
                .byte %00101000
                .byte %00101000
                .byte %00100110
                .byte %00100001
                .byte %00100001
                .byte %11001110

; 237
                .byte %00000000
                .byte %00000011
                .byte %00000000
                .byte %00000000
                .byte %00000000
                .byte %00000000
                .byte %00000000
                .byte %00000000

; 238
                .byte %00000000
                .byte %11101010
                .byte %10001011
                .byte %10001011
                .byte %10001010
                .byte %10001010
                .byte %10001010
                .byte %10001010                

; 239
                .byte %00000000
                .byte %00101111
                .byte %01101000
                .byte %11101000
                .byte %10101110
                .byte %10101000
                .byte %00101000
                .byte %00101111                
                
udgs_end:
                .cerror *>$b00,'gudgs overflow'
                