                .include "../submodules/beeb/include/beeb.s65"
                
*=$1100
                .cerror (udgs_end-udgs)%8!=0,""
                
start:
                ldx #0
chars_loop:
                lda #23
                jsr oswrch
ch=*+1
                lda #224
                jsr oswrch
                ldy #8
char_loop:
                lda udgs,x
                jsr oswrch
                inx
                dey
                bne char_loop
                inc ch
                cpx #udgs_end-udgs
                bcc chars_loop
                rts
                
; 224       = platform ==
; 225       = spring, row 0
; 226       = platform \=
; 227       = platform =/
; 228       = spikes
; 229       = spring, row 1
; 230...239 = fancy digits
; 240...242 = "BONUS"
; 243       = 2 dots

udgs:           .byte %11111111 ;224
                .byte %00011000 
                .byte %11111111 
                .byte %01100110 
                .byte %01100110 
                .byte %11111111 
                .byte %00011000 
                .byte %11111111 
                .byte %10101010 ;225
                .byte %11111100 
                .byte %00000010 
                .byte %01111001 
                .byte %10000101 
                .byte %01111110 
                .byte %00000010 
                .byte %01111001 
                .byte %11111111 ;226
                .byte %10011000 
                .byte %01111111 
                .byte %01100110 
                .byte %00100110 
                .byte %00111111 
                .byte %00011000 
                .byte %00000111 
                .byte %11111111 ;227
                .byte %00011001 
                .byte %11111110 
                .byte %01100110 
                .byte %01100100 
                .byte %11111100 
                .byte %00011000 
                .byte %11110000 
                .byte %10011001 ;228
                .byte %10011001 
                .byte %10011001 
                .byte %11011011 
                .byte %11011011 
                .byte %01011010 
                .byte %01011010 
                .byte %11111111 
                .byte %10000101 ;229
                .byte %01111110 
                .byte %00000010 
                .byte %01111001 
                .byte %10000101 
                .byte %01111110 
                .byte %10000001 
                .byte %01111110 
                .byte %11111110 ;230
                .byte %10000010 
                .byte %10000010 
                .byte %10000010 
                .byte %10000110 
                .byte %10000110 
                .byte %10000110 
                .byte %11111110 
                .byte %00001100 ;231
                .byte %00001100 
                .byte %00001100 
                .byte %00001100 
                .byte %00011100 
                .byte %00011100 
                .byte %00011100 
                .byte %00011100 
                .byte %11111110 ;232
                .byte %10000010 
                .byte %10000010 
                .byte %00000010 
                .byte %11111110 
                .byte %11000000 
                .byte %11000000 
                .byte %11111110 
                .byte %11111100 ;233
                .byte %10000100 
                .byte %10000100 
                .byte %00000100 
                .byte %00111110 
                .byte %10000110 
                .byte %10000110 
                .byte %11111110 
                .byte %11111100 ;234
                .byte %10000100 
                .byte %10000100 
                .byte %10000100 
                .byte %10000100 
                .byte %11111110 
                .byte %00001100 
                .byte %00001100 
                .byte %11111110 ;235
                .byte %10000000 
                .byte %10000000 
                .byte %11111110 
                .byte %00000110 
                .byte %00000110 
                .byte %10000110 
                .byte %11111110 
                .byte %11111110 ;236
                .byte %10000010 
                .byte %10000010 
                .byte %10000000 
                .byte %11111110 
                .byte %10000110 
                .byte %10000110 
                .byte %11111110 
                .byte %11111110 ;237
                .byte %00000010 
                .byte %00000010 
                .byte %00000010 
                .byte %00000110 
                .byte %00000110 
                .byte %00000110 
                .byte %00000110 
                .byte %01111100 ;238
                .byte %01000100 
                .byte %01000100 
                .byte %11111110 
                .byte %10000110 
                .byte %10000110 
                .byte %10000110 
                .byte %11111110 
                .byte %11111110 ;239
                .byte %10000010 
                .byte %10000010 
                .byte %11111110 
                .byte %00000110 
                .byte %00000110 
                .byte %00000110 
                .byte %00000110 
                .byte %00000000 ;240
                .byte %11100011 
                .byte %10010100 
                .byte %10010100 
                .byte %10100100 
                .byte %10010100 
                .byte %10010100 
                .byte %11100011 
                .byte %00000000 ;241
                .byte %00100101 
                .byte %10110101 
                .byte %10110101 
                .byte %10111101 
                .byte %10101101 
                .byte %10101101 
                .byte %00100100 
                .byte 0, $27, $28, $28, $26, $21, $21,$CE ;242
                .byte 0, 0, 0, 0, $33, $33, 0, 0          ;243
udgs_end: